# Generated by Django 5.2.1 on 2025-05-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_parsed_email_application_parsed_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
