# Generated by Django 5.2.1 on 2025-05-20 06:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_explanation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
