# Generated by Django 5.2.1 on 2025-06-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_match_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
