# Generated by Django 5.2.1 on 2026-09-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_ai_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='parsed_certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='parsed_education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='parsed_experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='parsed_projects_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
