# Generated by Django 6.0.1 on 2026-09-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='AI Recruit', max_length=255)),
                ('default_language', models.CharField(default='English (US)', max_length=50)),
                ('timezone', models.CharField(default='UTC (Coordinated Universal Time)', max_length=100)),
                ('smtp_server', models.CharField(default='smtp.mailgun.org', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_encryption', models.CharField(default='TLS', max_length=20)),
                ('from_email_address', models.EmailField(default='noreply@airecruit.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_2fa', models.BooleanField(default=True)),
                ('force_password_expiry', models.BooleanField(default=False)),
            ],
        ),
    ]
